package minesweeper;

import javax.swing.JOptionPane;

/**
 * A JDialog for viewing and editing game options.
 * @author Daniel
 */
public class Options extends javax.swing.JDialog {

    private Minesweeper parent;

    /**
     * Class Constructor
     * @param parent The Minesweeper responsible for this
     */
    public Options(Minesweeper parent) {
        super(parent, true);
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Ensures that the inputted values are safe to use
     * @param x
     * @param y
     * @param mines
     * @return 
     */
    private boolean validate(int x, int y, int mines) {
        return x > 8 && x <= 30
                && y > 8 && y <= 24
                && mines > 9 && mines <= (x - 1) * (y - 1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numMines = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Game Options");
        setResizable(false);

        numX.setText(""+Minesweeper.myWidth);

        jLabel1.setText("Horizontal");

        jLabel2.setText("Vertical");

        numY.setText(""+Minesweeper.myHeight);

        jLabel3.setText("Mines");

        numMines.setText(""+Minesweeper.Mines);

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numMines, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numY, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OKButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numMines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Called when the user clicks the Cancel option.
     */
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * Called when the user clicks the Cancel option.
     */
    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        int tempX, tempY, tempMines;
        try {
            tempX = Integer.parseInt(numX.getText());
            tempY = Integer.parseInt(numY.getText());
            tempMines = Integer.parseInt(numMines.getText());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "The boxes must be filled with numbers only.");
            return;
        }
        if (validate(tempX, tempY, tempMines)
                && (Minesweeper.myWidth != tempX
                || Minesweeper.myHeight != tempY
                || Minesweeper.Mines != tempMines)) {
            Minesweeper.myWidth = tempX;
            Minesweeper.myHeight = tempY;
            Minesweeper.Mines = tempMines;
            parent.newGame();
            parent.setCustom();
        } else if (!validate(tempX, tempY, tempMines)) {
            javax.swing.JOptionPane.showMessageDialog(null, "There must be between 9 and 30 horizontal spaces,\r\nbetween 9 and 24 vertical spaces,\r\nand between 10 and (x-1)(y-1) mines.");
            return;
        }
        this.dispose();
    }//GEN-LAST:event_OKButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField numMines;
    private javax.swing.JTextField numX;
    private javax.swing.JTextField numY;
    // End of variables declaration//GEN-END:variables
}
